import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const pages=JSON.parse(fs.readFileSync('data/pages.json','utf8')),titles=new Set(),headings=new Set(),descriptions=new Set(),graph=new Map();let links=0;
for(const page of pages){const filename=path.join('.',page.url,'index.html'),html=fs.readFileSync(filename,'utf8');
 assert.equal((html.match(/<h1\b/g)||[]).length,1,filename+' needs one H1');
 const title=html.match(/<title>(.*?)<\/title>/s)[1],h1=html.match(/<h1[^>]*>(.*?)<\/h1>/s)[1];assert.ok(!titles.has(title),'duplicate title '+title);titles.add(title);assert.ok(!headings.has(h1),'duplicate H1 '+h1);headings.add(h1);
 assert.ok(html.includes(`rel="canonical" href="https://worththemove.co.uk${page.url}"`),'canonical '+filename);const description=html.match(/name="description" content="([^"]+)"/)?.[1];assert.ok(description&&!descriptions.has(description),'missing/duplicate description '+filename);descriptions.add(description);for(const [key,value] of [['title',title],['description',description],['url','https://worththemove.co.uk'+page.url],['type','website']])assert.ok(html.includes(`property="og:${key}" content="${value}"`),'Open Graph '+key+' '+filename);assert.ok(!html.includes('noindex'),'noindex '+filename);
 assert.ok(!/lorem ipsum|TODO|AfterTaxTool|undefined|NaN/.test(html),'placeholder/nonfinite '+filename);
 graph.set(page.url,new Set());
 for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const url=match[1];if((!url.startsWith('/')&&!url.startsWith('#'))||url.startsWith('//'))continue;const parsed=new URL(url,'https://worththemove.co.uk'+page.url);let target=parsed.pathname;graph.get(page.url).add(target);const destination=path.join('.',target.endsWith('/')?target+'index.html':target);if(parsed.hash){const targetHTML=fs.readFileSync(destination,'utf8');assert.ok(targetHTML.includes(`id="${decodeURIComponent(parsed.hash.slice(1))}"`),'broken fragment '+url);}if(target.endsWith('/'))target+='index.html';assert.ok(fs.existsSync(path.join('.',target)),`${filename}: broken ${url}`);links++;}
 for(const match of html.matchAll(/<input ([^>]+)>/g)){const attrs=match[1],id=attrs.match(/id="([^"]+)"/)?.[1];assert.ok(id&&html.includes(`for="${id}"`),'unlabelled input '+filename);}
}
const sitemap=fs.readFileSync('sitemap.xml','utf8');assert.equal((sitemap.match(/<loc>/g)||[]).length,pages.length);assert.equal(new Set([...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1])).size,pages.length);for(const p of pages)assert.ok(sitemap.includes(`<loc>https://worththemove.co.uk${p.url}</loc>`));assert.equal(fs.readFileSync('CNAME','utf8').trim(),'worththemove.co.uk');assert.ok(fs.existsSync('.nojekyll'));assert.ok(fs.readFileSync('404.html','utf8').includes('noindex'));assert.equal(pages.length,54);const reached=new Set(['/']),queue=['/'];for(const u of queue)for(const next of graph.get(u)||[])if(graph.has(next)&&!reached.has(next)){reached.add(next);queue.push(next);}assert.equal(reached.size,54,'orphaned pages');const robots=fs.readFileSync('robots.txt','utf8');assert.ok(robots.includes('Allow: /')&&!robots.includes('Disallow: /'));assert.ok(robots.includes('Sitemap: https://worththemove.co.uk/sitemap.xml'));const htmlFiles=[];function walk(dir){for(const f of fs.readdirSync(dir,{withFileTypes:true})){if(f.name.startsWith('.')||f.name==='test-results')continue;const file=path.join(dir,f.name);if(f.isDirectory())walk(file);else if(f.name.endsWith('.html'))htmlFiles.push(file);}}walk('.');assert.equal(htmlFiles.length,55,'unexpected HTML route');
console.log(`PASS: ${pages.length} indexable pages; unique titles/descriptions/H1s, Open Graph, canonicals, exact sitemap membership, no orphans, ${links} internal asset/navigation links, labelled inputs, no placeholders. Root/CNAME/.nojekyll/404 checked.`);
